---
- name: Create a directory that will be used by the OpenShift installer to provide all the assets.
  file:
    dest: "ignition"
    state: "directory"
    mode: "0755"

- name: Setting up install-config template for installer.
  template:
    src: "install-config.yaml"
    dest: "ignition/{{ item }}"
  loop:
    - "install-config.yaml"
    - "install-config.yaml.orig"

- name: Invoking the installer to get manifests.
  shell:
    cmd: openshift-install create manifests --dir ignition

- name: Remove the manifest files that define the MachineSets because create and manage these resources yourself.
  file:
    path: "{{ item }}"
    state: "absent"
  loop:
    - "ignition/99_openshift-cluster-api_master-machines-0.yaml"
    - "ignition/99_openshift-cluster-api_master-machines-1.yaml"
    - "ignition/99_openshift-cluster-api_master-machines-2.yaml"
    - "ignition/99_openshift-cluster-api_worker-machineset-0.yaml"
    - "ignition/99_openshift-machine-api_master-control-plane-machine-set.yaml"

- name: Create a Butane config including the chrony time service contents.
  template:
    src: "chrony.bu"
    dest: "ignition/openshift/99-{{ item }}-chrony.bu"
  loop:
    - "master"
    - "worker"

- name: Generate a chrony time service object file.
  shell:
    cmd: butane ignition/openshift/99-{{ item }}-chrony.bu -o ignition/openshift/99-{{ item }}-chrony.yaml
  loop:
    - "master"
    - "worker"

- name: Remove a Butane config including the chrony time service contents.
  file:
    path: "ignition/openshift/99-{{ item }}-chrony.bu"
    state: "absent"
  loop:
    - "master"
    - "worker"

- name: Invoking the installer to get manifests.
  shell:
    cmd: openshift-install create ignition-configs --dir ignition

- name: Create secondary Ignition config file for bootstrap node.
  template:
    src: "merge-bootstrap.ign"
    dest: "ignition/merge-bootstrap.ign"
