additionalTrustBundlePolicy: Proxyonly
apiVersion: v1
baseDomain: {{ openshift_domain }}
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: {{ openshift_cluster }}
networking:
  clusterNetwork:
  - cidr: {{ openshift_network.network | default("10.128.0.0/14") }}
    hostPrefix: {{ openshift_network.hostprefix | default("23") }}
  machineNetwork:
  - cidr: {{ openshift_network.machine }}
  networkType: OVNKubernetes
  serviceNetwork: [{{ openshift_network.service }}]
platform:
  vsphere:
    failureDomains: 
    - name: default
      region: default
      server: "{{ openshift_vsphere.vcenter }}"
      topology:
        computeCluster: "/{{ openshift_vsphere.datacenter }}/host/{{ openshift_vsphere.cluster }}"
        datacenter: "{{ openshift_vsphere.datacenter }}"
        datastore: "/{{ openshift_vsphere.datacenter }}/datastore/{{ openshift_vsphere.datastore }}" 
        networks: {{ openshift_vsphere.networks }}
      zone: default
    vcenters:
    - datacenters:
      - "{{ openshift_vsphere.datacenter }}"
      password: {{ openshift_vsphere.password }}
      port: 443
      server: {{ openshift_vsphere.vcenter }}
      user: "{{ openshift_vsphere.user }}@{{ openshift_vsphere.vcenter }}"
    diskType: {{ openshift_vsphere.disktype | default('thin') }}
    apiVIPs: [{{ openshift_network.apivips }}]
    ingressVIPs: [{{ openshift_network.ingressvips }}]
publish: External
pullSecret: '{{ openshift_cr.pullsecret }}'
fips: false
capabilities:
  baselineCapabilitySet: None
  additionalEnabledCapabilities: {{ openshift_capabilities }}
sshKey: '{{ openshift_node.sshkey }}'
{% if openshift_cr.additionaltrustbundle is defined %}
additionalTrustBundle: |-
{{ openshift_cr.additionaltrustbundle | indent( width=2, first=True ) }}
{% endif %}
{% if openshift_cr.imagedigestsources is defined and openshift_cr.imagedigestsources | length > 0 %}
imageDigestSources:
{% for i in openshift_cr.imagedigestsources %}
- mirrors: {{ i.mirrors }}
  source: {{ i.source }}
{% endfor %}
{% endif %}